#!/bin/bash
echo $'\e[32;1m'"---installing upgrade"$'\e[0m'
apt update && apt upgrade -y
echo $'\e[32;1m'"---installing git neovim nodejs wget "$'\e[0m'
apt install wget neovim git nodejs -y
echo $'\e[32;1m'"---Downloading plugin "$'\e[0m'
mkdir -p .config/nvim > /dev/null 2>&1
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
wget https://raw.githubusercontent.com/brxxlstxrs/VSCode/main/init.vim && mv init.vim .config/nvim
echo $'\e[32;1m'"---Opennig config in neovin"$'\e[0m'
sleep 3
nvim .config/nvim/init.vim
